# Generated by Django 3.0.5 on 2020-07-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SudokuState',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=200)),
                ('shape', models.CharField(max_length=200)),
            ],
        ),
    ]
